### ISSUE TITLE
How do I install this on my acer r13.

### ISSUE THREAD

**Issue by Linuxnoob01** [LelouBil/linux-kernel-powervr-rogue-6XT#1]
Sincere aplogies I found this on google ,I would like to use linux on my chromebook in my degoogle proces.
could the creator of this point me in the right direction of reading material how to install linux on my acer r13.

adriaancarabao@gmail.com

**Comment by LelouBil** [comment]
Hello, this is actually a fork of this repository : https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel
from hexdump0815.

This one is not in a usable state as I am actually trying to make the GPU drivers work for the acer r13.

You can use hexdump's images here : https://github.com/hexdump0815/imagebuilder/tree/main/systems/chromebook_oak

To install them you can flash one of them on a USB stick or a SD card, then at the chrome OS developer screen press CTRL-U, and it will boot to it. If you want to completely remove chromeos from the chromebook, you can then flash it on the internal storage, but don't forget to resize the data partition as it is very small by default.

As I said above, GPU acceleration is missing, but I'm working on it.
